# -*- coding: utf-8 -*-
"""Data analystic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12fMgw8m3QIKNannevn5Vfou_db2iyn2m
"""

import pandas as pd

titanic =pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Titanic.csv')

titanic.head()

titanic.info()

titanic.describe()

#1 import liberary
import pandas as pd

#2 import data
salary = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Salary%20Data.csv')

salary.head()

salary.info()

salary.describe()

salary.columns

salary.shape

#3 Define target: target (x) and features (y)
salary.columns

y = salary ['Salary']
x = salary [['Experience Years']]

salary.shape

x.shape

y.shape

#4 train and test
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7 ,random_state=2529 )

x_train.shape,x_test.shape,y_train.shape,y_test.shape

x_train